# Generated by Django 3.0.3 on 2020-03-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200323_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
